#include <stdio.h>
#include <stdlib.h>

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	int n,guess;
	printf("-------------------------------------------------------------\n");
	printf("             INTRODUCTION TO PLAY A GAME                     \n");
	printf("-------------------------------------------------------------\n");
	printf("         *.USER WILL HAVE A CHANCE OF 5                      \n");
	printf("         *.A number will be generated by computer within 50  \n");
	printf("         *.If user fail to guess the computer will display   \n");
	printf("-------------------------------------------------------------\n");
	printf("enter the number b/w 1 to 50");
	scanf("%d",&guess);
	guess=rand()%50+1;
	printf("")
	return 0;
}
